#!/bin/bash


tmpdir=$PWD/tmp
mkdir $tmpdir

containsElement () {
  local e
  for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 0; done
  return 1
}

BUILD=./build_package
PACKAGES=
DIR=/tmp/
JOBS=3
PREFIX=$HOME/local/
CC=gcc
FC=gfortran

ACTION="$1"
shift

while [[ $# -gt 1 ]]; do
key="$1"

case $key in
    -j|--jobs)
    JOBS="$2"
    shift # past argument
    ;;
    -j=*|--jobs=*)
    JOBS="${key#*=}"
    ;;
    -p|--prefix)
    PREFIX="$2"
    shift # past argument
    ;;
    -p=*|--prefix=*)
    PREFIX="${key#*=}"
    ;;
    --fc|--fortran-compiler)
    FC="$2"
    shift # past argument
    ;;
    --fc=*|--fortran-compiler=)
    FC="${key#*=}"
    ;;
    --cc|--c-compiler)
    CC="$2"
    shift # past argument
    ;;
    --cc=*|--c-compiler=)
    CC="${key#*=}"
    ;;
    --verbose)
    VERBOSE=YES
    ;;
    *)
	break
            # unknown option
    ;;
esac
shift # past argument or value
done

PACKAGES=( "$@" )

echo action "${ACTION}"
echo what "${PACKAGES}"
echo JOBS "${JOBS}"
echo VERBOSE "${VERBOSE}"

for arg in "${PACKAGES[@]}"; do
    echo package "$arg"
done

HDF5_VERSION=1.8.15
HDF5_URL=http://www.hdfgroup.org/ftp/HDF5/releases/hdf5-$HDF5_VERSION/src/hdf5-$HDF5_VERSION.tar.gz


NETCDF_VERSION=4.3.3.1
NETCDF_URL=http://www.unidata.ucar.edu/downloads/netcdf/ftp/netcdf-$NETCDF_VERSION.tar.gz

NETCDF_FORTRAN_VERSION=4.4.4
NETCDF_FORTRAN_URL=ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-fortran-$NETCDF_FORTRAN_VERSION.tar.gz



for i in hdf5 netcdf; do
    if containsElement "hdf5" "${PACKAGES[@]}"; then
        $BUILD --package $HDF5_URL --prefix $PREFIX --name hdf5 \
	    --configArgs "CC=$CC --enable-shared --enable-static"                
    fi

    if containsElement "netcdf" "${PACKAGES[@]}"; then
	$BUILD --package $NETCDF_URL --prefix $PREFIX  --name netcdf --check yes \
	      --configArgs "CC=$CC FC=$FC CPPFLAGS=-I$PREFIX/include  LDFLAGS=-L$PREFIX/lib"	
    fi

    if containsElement "netcdf-fortran" "${PACKAGES[@]}"; then
	$BUILD --package $NETCDF_FORTRAN_URL --prefix $PREFIX  --name netcdf --check yes \
	      --configArgs "CC=$CC FC=$FC CPPFLAGS=-I$PREFIX/include  LDFLAGS=-L$PREFIX/lib"	
    fi

done

